spring:
  profiles:
    active: dev
server:
  port: 9101


# 下面数据待定
---
spring:
  profiles: dev
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3316/mysql_demo?&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      password: test
      username: test
    slave:
      jdbc-url: jdbc:mysql://localhost:3326/mysql_demo?&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      password: test
      username: test
