spring:
  profiles:
    active: dev
server:
  port: 9102

mybatis:
  mapper-locations: classpath:mapper/*.xml


# 下面数据待定
---
spring:
  profiles: dev
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds0,ds1,ds2
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        password: test
        username: test
      ds0:
        jdbc-url: jdbc:mysql://localhost:3316/mysql_demo?&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      ds1:
        jdbc-url: jdbc:mysql://localhost:3326/mysql_demo?&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      ds2:
        jdbc-url: jdbc:mysql://localhost:3336/mysql_demo?&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    rules:
#      primary-replica-replication:
      replica-query:
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
            props:
              default: 0
        data-sources:
          pr_ds:
            primary-data-source-name: ds0
            replica-data-source-names: ds1,ds2
            load-balancer-name: round-robin
    props:
      sql-show: true
