spring:
  profiles:
    active: dev
server:
  port: 9102

mybatis:
  mapper-locations: classpath:mapper/*.xml


# 下面数据待定
---
spring:
  profiles: dev
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds0,ds1
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        password: test
        username: test
      ds0:
        jdbc-url: jdbc:mysql://localhost:3316/mysql_demo?&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      ds1:
        jdbc-url: jdbc:mysql://localhost:3346/mysql_demo?&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    rules:
      sharding:
        tables:
          order:
            actual-data-nodes: ds$->{0..1}.order_$->{1..16}
            database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: database-inline
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: table-inline
            key-generate-strategy:
              key-generator-name: snow-flake
              column: id
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{user_id % 2}
          table-inline:
            type: INLINE
            props:
              algorithm-expression: order_$->{id %16}
        key-generators:
          snow-flake:
            type: SNOWFLAKE
            props:
              worker-id: 123
    props:
      sql-show: true
